type category {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type career_work {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type career_work_feedback {
  feedback: String
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  advice5: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type community {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type community_feedback {
  feedback: String
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  advice5: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type environment {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type environment_feedback {
  feedback: String
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  advice5: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type family_friends {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type family_friends_feedback {
  feedback: String
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  advice5: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type fun_relaxation {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type fun_relaxation_feedback {
  feedback: String
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  advice5: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type growth_learning {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type growth_learning_feedback {
  feedback: String
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  advice5: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type health_fitness {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type health_fitness_feedback {
  feedback: String
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  advice5: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type money_finances {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type money_finances_feedback {
  feedback: String
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  advice5: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type partner_love {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type partner_love_feedback {
  feedback: String
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  advice5: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type spirituality {
  username: String
  score: Float
  notes: String
  action_plan: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type spirituality_feedback {
  feedback: String
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  advice5: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type overall_score {
  username: String
  overall_score: Float
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type overall_advice {
  advice1: String
  advice2: String
  advice3: String
  advice4: String
  id: ID!
  created_at: DateTime
  user_ref: Int
}

type users {
  username: String
  email: String
  provider: String
  password: String 
  id: ID!
  created_at: DateTime
  isActive: Boolean
}

type UserData {
  username: String
  email: String
  provider: String
  password: String 
  id: ID!
  created_at: DateTime
  career_work: [career_work]
    @materializer(
      query: "careerWorkListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  career_work_feedback: [career_work_feedback]
    @materializer(
      query: "careerWorkFeedbackListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  community: [community]
    @materializer(
      query: "communityListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  community_feedback: [community_feedback]
    @materializer(
      query: "communityFeedbackListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  environment: [environment]
    @materializer(
      query: "environmentListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  environment_feedback: [environment_feedback]
    @materializer(
      query: "environmentFeedbackListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  family_friends: [family_friends]
    @materializer(
      query: "familyFriendsListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  family_friends_feedback: [family_friends_feedback]
    @materializer(
      query: "familyFriendsFeedbackListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  fun_relaxation: [fun_relaxation]
    @materializer(
      query: "funRelaxationListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  fun_relaxation_feedback: [fun_relaxation_feedback]
    @materializer(
      query: "funRelaxationFeedbackListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  growth_learning: [growth_learning]
    @materializer(
      query: "growthLearningListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  growth_learning_feedback: [growth_learning_feedback]
    @materializer(
      query: "growthLearningFeedbackListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  health_fitness: [health_fitness]
    @materializer(
      query: "healthFitnessListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  health_fitness_feedback: [health_fitness_feedback]
    @materializer(
      query: "healthFitnessFeedbackListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  money_finances: [money_finances]
    @materializer(
      query: "moneyFinancesListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  money_finances_feedback: [money_finances_feedback]
    @materializer(
      query: "moneyFinancesFeedbackListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  partner_love: [partner_love]
    @materializer(
      query: "partnerLoveListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  partner_love_feedback: [partner_love_feedback]
    @materializer(
      query: "partnerLoveFeedbackListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  spirituality: [spirituality]
    @materializer(
      query: "spiritualityListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  spirituality_feedback: [spirituality_feedback]
    @materializer(
      query: "spiritualityFeedbackListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  overall_score: [overall_score]
    @materializer(
      query: "overallScoreListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
  overall_advice: [overall_advice]
    @materializer(
      query: "overallAdviceListByUserId"
      arguments: [{name: "user_ref", field: "id"}]
    )
}


"""
The following queries are just a set of examples of how to access your schema.
Feel free to modify them or aggregate more.
"""
type Query {
  " Queries for type 'career_work' "
  # index.graphql

########### Query User ############
  userByEmail(email: String!): users
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "users"
      WHERE "email" = $1
      """
      configuration: "postgresql_config"
    )


  ########### Query By User ############

  userDataById(id: ID!): UserData
  @dbquery(
    type: "postgresql"
    schema: "public"
    query: """
    SELECT *
    FROM "users"
    WHERE "id" = $1
    """
    configuration: "postgresql_config"
  )

  careerWorkListByUser(username: String!): [career_work]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "career_work"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

    careerWorkListByUserId(user_ref: ID!): [career_work]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "career_work"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

    careerWorkFeedbackListByUserId(user_ref: ID!): [career_work_feedback]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "career_work_feedback"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  communityListByUser(username: String!): [community]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "community"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  communityListByUserId(user_ref: ID!): [community]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "community"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  communityFeedbackListByUserId(user_ref: ID!): [community_feedback]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "community_feedback"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  environmentListByUser(username: String!): [environment]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "environment"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  environmentListByUserId(user_ref: ID!): [environment]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "environment"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  environmentFeedbackListByUserId(user_ref: ID!): [environment_feedback]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "environment_feedback"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  familyFriendsListByUser(username: String!): [family_friends]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "family_friends"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  familyFriendsListByUserId (user_ref: ID!): [family_friends]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "family_friends"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  familyFriendsFeedbackListByUserId (user_ref: ID!): [family_friends_feedback]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "family_friends_feedback"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )


  funRelaxationListByUser(username: String!): [fun_relaxation]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "fun_relaxation"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  funRelaxationListByUserId(user_ref: ID!): [fun_relaxation]
  @dbquery(
    type: "postgresql"
    schema: "public"
    query: """
    SELECT *
    FROM "fun_relaxation"
    WHERE "user_ref" = $1
    ORDER BY "created_at" DESC
    """
    configuration: "postgresql_config"
  )

  funRelaxationFeedbackListByUserId(user_ref: ID!): [fun_relaxation_feedback]
  @dbquery(
    type: "postgresql"
    schema: "public"
    query: """
    SELECT *
    FROM "fun_relaxation_feedback"
    WHERE "user_ref" = $1
    ORDER BY "created_at" DESC
    """
    configuration: "postgresql_config"
  )

  growthLearningListByUser(username: String!): [growth_learning]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "growth_learning"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  growthLearningListByUserId(user_ref: ID!): [growth_learning]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "growth_learning"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  growthLearningFeedbackListByUserId(user_ref: ID!): [growth_learning_feedback]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "growth_learning_feedback"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )


  healthFitnessListByUser(username: String!): [health_fitness]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "health_fitness"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  healthFitnessListByUserId(user_ref: ID!): [health_fitness]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "health_fitness"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  healthFitnessFeedbackListByUserId(user_ref: ID!): [health_fitness_feedback]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "health_fitness_feedback"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  moneyFinancesListByUser(username: String!): [money_finances]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "money_finances"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  moneyFinancesListByUserId(user_ref: ID!): [money_finances]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "money_finances"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  moneyFinancesFeedbackListByUserId(user_ref: ID!): [money_finances_feedback]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "money_finances_feedback"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  partnerLoveListByUser(username: String!): [partner_love]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "partner_love"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  partnerLoveListByUserId(user_ref: ID!): [partner_love]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "partner_love"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  partnerLoveFeedbackListByUserId(user_ref: ID!): [partner_love_feedback]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "partner_love_feedback"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  spiritualityListByUser(username: String!): [spirituality]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "spirituality"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  spiritualityListByUserId(user_ref: ID!): [spirituality]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "spirituality"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  spiritualityFeedbackListByUserId(user_ref: ID!): [spirituality_feedback]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "spirituality_feedback"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  overallScoreListByUser(username: String!): [overall_score]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "overall_score"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  overallScoreListByUserId(user_ref: ID!): [overall_score]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "overall_score"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  overallAdviceListByUser(username: String!): [overall_advice]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "overall_advice"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  overallAdviceListByUserId(user_ref: ID!): [overall_advice]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "overall_advice"
      WHERE "user_ref" = $1
      ORDER BY "created_at" DESC
      """
      configuration: "postgresql_config"
    )

  ########### Query by Latest User Input ##########
  careerWorkListByUserLatest(username: String!): [career_work]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "career_work"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  communityListByUserLatest(username: String!): [community]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "community"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  environmentListByUserLatest(username: String!): [environment]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "environment"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  familyFriendsListByUserLatest(username: String!): [family_friends]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "family_friends"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  funRelaxationListByUserLatest(username: String!): [fun_relaxation]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "fun_relaxation"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  growthLearningListByUserLatest(username: String!): [growth_learning]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "growth_learning"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  healthFitnessListByUserLatest(username: String!): [health_fitness]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "health_fitness"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  moneyFinancesListByUserLatest(username: String!): [money_finances]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "money_finances"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  partnerLoveListByUserLatest(username: String!): [partner_love]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "partner_love"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  spiritualityListByUserLatest(username: String!): [spirituality]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "spirituality"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  career_work(id: ID!): career_work
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "career_work"
      configuration: "postgresql_config"
    )
  career_workList: [career_work]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "career_work"
      configuration: "postgresql_config"
    )
  career_workPaginatedList(first: Int, after: Int): [career_work]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "created_at", "id", "score", "username", "user_ref" FROM "career_work" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )
  " Queries for type 'community' "
  community(id: ID!): community
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "community"
      configuration: "postgresql_config"
    )
  communityList: [community]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "community"
      configuration: "postgresql_config"
    )

  # communityListByUser(username: String!): [community]
  #   @dbquery(
  #     type: "postgresql"
  #     schema: "public"
  #     query: """
  #     select * from "community" where "username" = $1
  #     """
  #     configuration: "postgresql_config"
  #   )

  communityListById(id: ID!): [community]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      select * from "community" where "id" = $1
      """
      configuration: "postgresql_config"
    )

  categoryListByUser(username: String!, tableName: String!): [category]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "tableName"
      WHERE "username" = $1
      """
      configuration: "postgresql_config"
    )

  categoryListByUserLatest(username: String!, tableName: String!): [category]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "tableName"
      WHERE "username" = $1
      ORDER BY "created_at" DESC
      LIMIT 1
      """
      configuration: "postgresql_config"
    )

  communityListByUserDateRange(
    username: String!
    startDate: String!
    endDate: String!
  ): [community]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT *
      FROM "community"
      WHERE "username" = $1
        AND "created_at" >= $2
        AND "created_at" <= $3
      """
      configuration: "postgresql_config"
    )

  communityPaginatedList(first: Int, after: Int): [community]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "created_at", "id", "score", "username", "user_ref" FROM "community" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )
  " Queries for type 'environment' "
  environment(id: ID!): environment
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "environment"
      configuration: "postgresql_config"
    )
  environmentList: [environment]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "environment"
      configuration: "postgresql_config"
    )
  environmentPaginatedList(first: Int, after: Int): [environment]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "created_at", "id", "score", "username", "user_ref" FROM "environment" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )
  " Queries for type 'family_friends' "
  family_friends(id: ID!): family_friends
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "family_friends"
      configuration: "postgresql_config"
    )
  family_friendsList: [family_friends]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "family_friends"
      configuration: "postgresql_config"
    )
  family_friendsPaginatedList(first: Int, after: Int): [family_friends]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "created_at", "id", "score", "username", "user_ref" FROM "family_friends" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )
  " Queries for type 'fun_relaxation' "
  fun_relaxation(id: ID!): fun_relaxation
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "fun_relaxation"
      configuration: "postgresql_config"
    )
  fun_relaxationList: [fun_relaxation]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "fun_relaxation"
      configuration: "postgresql_config"
    )
  fun_relaxationPaginatedList(first: Int, after: Int): [fun_relaxation]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "created_at", "id", "score", "username", "user_ref" FROM "fun_relaxation" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )
  " Queries for type 'growth_learning' "
  growth_learning(id: ID!): growth_learning
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "growth_learning"
      configuration: "postgresql_config"
    )
  growth_learningList: [growth_learning]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "growth_learning"
      configuration: "postgresql_config"
    )
  growth_learningPaginatedList(first: Int, after: Int): [growth_learning]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "created_at", "id", "score", "username", "user_ref" FROM "growth_learning" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )
  " Queries for type 'health_fitness' "
  health_fitness(id: ID!): health_fitness
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "health_fitness"
      configuration: "postgresql_config"
    )
  health_fitnessList: [health_fitness]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "health_fitness"
      configuration: "postgresql_config"
    )
  health_fitnessPaginatedList(first: Int, after: Int): [health_fitness]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "created_at", "id", "score", "username", "user_ref" FROM "health_fitness" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )
  " Queries for type 'money_finances' "
  money_finances(id: ID!): money_finances
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "money_finances"
      configuration: "postgresql_config"
    )
  money_financesList: [money_finances]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "money_finances"
      configuration: "postgresql_config"
    )
  money_financesPaginatedList(first: Int, after: Int): [money_finances]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "created_at", "id", "score", "username", "user_ref" FROM "money_finances" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )
  " Queries for type 'overall_score' "
  overall_score(id: ID!): overall_score
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "overall_score"
      configuration: "postgresql_config"
    )
  overall_scoreList: [overall_score]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "overall_score"
      configuration: "postgresql_config"
    )
  overall_scorePaginatedList(first: Int, after: Int): [overall_score]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "career_work_score", "community_score", "created_at", "environment_score", "family_friends_score", "fun_relaxation_score", "growth_learning_score", "health_fitness_score", "id", "money_finances_score", "overall_score", "partner_love_score", "spirituality_score", "username" FROM "overall_score" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )


" Queries for type 'overall_advice' "
  overall_advice(user_ref: ID!): overall_advice
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "overall_advice"
      configuration: "postgresql_config"
    )
  overall_adviceList: [overall_advice]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "overall_advice"
      configuration: "postgresql_config"
    )
  overall_advicePaginatedList(first: Int, after: Int): [overall_advice]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "advice1", "advice2", "advice3", "advice4", "created_at", "id", "user_ref" FROM "overall_advice" ORDER BY "created_at" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )


  " Queries for type 'partner_love' "
  partner_love(id: ID!): partner_love
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "partner_love"
      configuration: "postgresql_config"
    )
  partner_loveList: [partner_love]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "partner_love"
      configuration: "postgresql_config"
    )
  partner_lovePaginatedList(first: Int, after: Int): [partner_love]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "created_at", "environment_score", "id", "username", "user_ref" FROM "partner_love" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )
  " Queries for type 'spirituality' "
  spirituality(id: ID!): spirituality
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "spirituality"
      configuration: "postgresql_config"
    )
  spiritualityList: [spirituality]
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "spirituality"
      configuration: "postgresql_config"
    )
  spiritualityPaginatedList(first: Int, after: Int): [spirituality]
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      SELECT "created_at", "id", "score", "username", "user_ref" FROM "spirituality" ORDER BY "id" LIMIT $1 OFFSET $2
      """
      configuration: "postgresql_config"
    )
}

"""
The following mutations are just a set of examples of how to access your schema.
Feel free to modify them or aggregate more.
"""
type Mutation {
  " Mutations for type 'career_work' "
  deleteCareer_work(id: ID!): career_work
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "career_work"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertCareer_work(
    username: String
    score: Float
    notes: String
    action_plan: String
    created_at: DateTime
    user_ref: Int
  ): career_work
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "career_work"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateCareer_work(
    id: ID!
    created_at: DateTime
    score: Float
    notes: String
    action_plan: String
    username: String
    user_ref: Int
  ): career_work
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "career_work" SET
        "created_at" = COALESCE($2, "created_at"),
        "score" = COALESCE($3, "score"),
        "username" = COALESCE($4, "username")
        "notes" = COALESCE($5, "notes")
        "action_plan" = COALESCE($6, "action_plan")
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )

" Mutations for type 'career_work_feedback' "
  deleteCareer_work_feedback(id: ID!): career_work_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "career_work_feedback"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertCareer_work_feedback(
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ):
  career_work_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "career_work_feedback"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateCareer_work_feedback(
    id: ID!
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ): 
  career_work_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "career_work_feedback" SET
        "feedback" = COALESCE($2, "feedback")
        "advice1" = COALESCE($3, "advice1"),
        "advice2" = COALESCE($4, "advice2"),
        "advice3" = COALESCE($5, "advice3"),
        "advice4" = COALESCE($6, "advice4"),
        "advice5" = COALESCE($7, "advice5"),
        "created_at" = COALESCE($8, "created_at"),
        "user_ref" = COALESCE($9, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )

  " Mutations for type 'community' "
  deleteCommunity(id: ID!): community
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "community"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertCommunity(
    username: String
    score: Float
    notes: String
    action_plan: String
    created_at: DateTime
    user_ref: Int
  ): community
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "community"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateCommunity(
    id: ID!
    created_at: DateTime
    score: Float
    notes: String
    action_plan: String
    username: String
    user_ref: Int
  ): community
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "community" SET
        "created_at" = COALESCE($2, "created_at"),
        "score" = COALESCE($3, "score"),
        "username" = COALESCE($4, "username")
        "notes" = COALESCE($5, "notes")
        "action_plan" = COALESCE($6, "action_plan")
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


" Mutations for type 'community_feedback' "
  deleteCommunity_feedback(id: ID!): community_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "community_feedback"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertCommunity_feedback(
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ):
  community_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "community_feedback"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateCommunity_feedback(
    id: ID!
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ): 
  community_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "community_feedback" SET
        "feedback" = COALESCE($2, "feedback")
        "advice1" = COALESCE($3, "advice1"),
        "advice2" = COALESCE($4, "advice2"),
        "advice3" = COALESCE($5, "advice3"),
        "advice4" = COALESCE($6, "advice4"),
        "advice5" = COALESCE($7, "advice5"),
        "created_at" = COALESCE($8, "created_at"),
        "user_ref" = COALESCE($9, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )

  " Mutations for type 'environment' "
  deleteEnvironment(id: ID!): environment
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "environment"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertEnvironment(
    username: String
    score: Float
    notes: String
    action_plan: String
    created_at: DateTime
    user_ref: Int
  ): environment
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "environment"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateEnvironment(
    id: ID!
    created_at: DateTime
    score: Float
    notes: String
    action_plan: String
    username: String
    user_ref: Int
  ): environment
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "environment" SET
        "created_at" = COALESCE($2, "created_at"),
        "score" = COALESCE($3, "score"),
        "username" = COALESCE($4, "username")
        "notes" = COALESCE($5, "notes")
        "action_plan" = COALESCE($6, "action_plan")
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


" Mutations for type 'environment_feedback' "
  deleteEvironment_feedback(id: ID!): environment_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "environment_feedback"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertEnvironment_feedback(
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ):
  environment_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "environment_feedback"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateEnvironment_feedback(
    id: ID!
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ): 
  environment_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "environment_feedback" SET
        "feedback" = COALESCE($2, "feedback")
        "advice1" = COALESCE($3, "advice1"),
        "advice2" = COALESCE($4, "advice2"),
        "advice3" = COALESCE($5, "advice3"),
        "advice4" = COALESCE($6, "advice4"),
        "advice5" = COALESCE($7, "advice5"),
        "created_at" = COALESCE($8, "created_at"),
        "user_ref" = COALESCE($9, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


  " Mutations for type 'family_friends' "
  deleteFamily_friends(id: ID!): family_friends
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "family_friends"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertFamily_friends(
    username: String
    score: Float
    notes: String
    action_plan: String
    created_at: DateTime
    user_ref: Int
  ): family_friends
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "family_friends"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateFamily_friends(
    id: ID!
    created_at: DateTime
    score: Float
    notes: String
    action_plan: String
    username: String
    user_ref: Int
  ): family_friends
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "family_friends" SET
        "created_at" = COALESCE($2, "created_at"),
        "score" = COALESCE($3, "score"),
        "username" = COALESCE($4, "username")
        "notes" = COALESCE($5, "notes")
        "action_plan" = COALESCE($6, "action_plan")
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


" Mutations for type 'family_friends_feedback' "
  deleteFamily_friends_feedback(id: ID!): family_friends_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "family_friends_feedback"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertFamily_friends_feedback(
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ):
  family_friends_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "family_friends_feedback"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateFamily_friends_feedback(
    id: ID!
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ): 
  family_friends_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "family_friends_feedback" SET
        "feedback" = COALESCE($2, "feedback")
        "advice1" = COALESCE($3, "advice1"),
        "advice2" = COALESCE($4, "advice2"),
        "advice3" = COALESCE($5, "advice3"),
        "advice4" = COALESCE($6, "advice4"),
        "advice5" = COALESCE($7, "advice5"),
        "created_at" = COALESCE($8, "created_at"),
        "user_ref" = COALESCE($9, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


  " Mutations for type 'fun_relaxation' "
  deleteFun_relaxation(id: ID!): fun_relaxation
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "fun_relaxation"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertFun_relaxation(
    username: String
    score: Float
    notes: String
    action_plan: String
    created_at: DateTime
    user_ref: Int
  ): fun_relaxation
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "fun_relaxation"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateFun_relaxation(
    id: ID!
    created_at: DateTime
    score: Float
    notes: String
    action_plan: String
    username: String
    user_ref: Int
  ): fun_relaxation
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "fun_relaxation" SET
        "created_at" = COALESCE($2, "created_at"),
        "score" = COALESCE($3, "score"),
        "username" = COALESCE($4, "username")
        "notes" = COALESCE($5, "notes")
        "action_plan" = COALESCE($6, "action_plan")
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


" Mutations for type 'fun_relaxation_feedback' "
  deleteFun_relaxation_feedback(id: ID!): fun_relaxation_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "fun_relaxation_feedback"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertFun_relaxation_feedback(
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ):
  fun_relaxation_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "fun_relaxation_feedback"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateFun_relaxation_feedback(
    id: ID!
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ): 
  fun_relaxation_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "fun_relaxation_feedback" SET
        "feedback" = COALESCE($2, "feedback")
        "advice1" = COALESCE($3, "advice1"),
        "advice2" = COALESCE($4, "advice2"),
        "advice3" = COALESCE($5, "advice3"),
        "advice4" = COALESCE($6, "advice4"),
        "advice5" = COALESCE($7, "advice5"),
        "created_at" = COALESCE($8, "created_at"),
        "user_ref" = COALESCE($9, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


  " Mutations for type 'growth_learning' "
  deleteGrowth_learning(id: ID!): growth_learning
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "growth_learning"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertGrowth_learning(
    username: String
    score: Float
    notes: String
    action_plan: String
    created_at: DateTime
    user_ref: Int
  ): growth_learning
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "growth_learning"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateGrowth_learning(
    id: ID!
    created_at: DateTime
    score: Float
    notes: String
    action_plan: String
    username: String
    user_ref: Int
  ): growth_learning
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "growth_learning" SET
        "created_at" = COALESCE($2, "created_at"),
        "score" = COALESCE($3, "score"),
        "username" = COALESCE($4, "username")
        "notes" = COALESCE($5, "notes")
        "action_plan" = COALESCE($6, "action_plan")
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


" Mutations for type 'growth_learning_feedback' "
  deleteGrowth_learning_feedback(id: ID!): growth_learning_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "growth_learning_feedback"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertGrowth_learning_feedback(
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ):
  growth_learning_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "growth_learning_feedback"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateGrowth_learning_feedback(
    id: ID!
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ): 
  growth_learning_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "growth_learning_feedback" SET
        "feedback" = COALESCE($2, "feedback")
        "advice1" = COALESCE($3, "advice1"),
        "advice2" = COALESCE($4, "advice2"),
        "advice3" = COALESCE($5, "advice3"),
        "advice4" = COALESCE($6, "advice4"),
        "advice5" = COALESCE($7, "advice5"),
        "created_at" = COALESCE($8, "created_at"),
        "user_ref" = COALESCE($9, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


  " Mutations for type 'health_fitness' "
  deleteHealth_fitness(id: ID!): health_fitness
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "health_fitness"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertHealth_fitness(
    username: String
    score: Float
    notes: String
    action_plan: String
    created_at: DateTime
    user_ref: Int
  ): health_fitness
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "health_fitness"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateHealth_fitness(
    id: ID!
    created_at: DateTime
    score: Float
    notes: String
    action_plan: String
    username: String
    user_ref: Int
  ): health_fitness
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "health_fitness" SET
        "created_at" = COALESCE($2, "created_at"),
        "score" = COALESCE($3, "score"),
        "username" = COALESCE($4, "username")
        "notes" = COALESCE($5, "notes")
        "action_plan" = COALESCE($6, "action_plan")
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


" Mutations for type 'health_fitness_feedback' "
  deleteHealth_fitness_feedback(id: ID!): health_fitness_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "health_fitness_feedback"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertHealth_fitness_feedback(
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ):
  health_fitness_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "health_fitness_feedback"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateHealth_fitness_feedback(
    id: ID!
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ): 
  health_fitness_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "health_fitness_feedback" SET
        "feedback" = COALESCE($2, "feedback")
        "advice1" = COALESCE($3, "advice1"),
        "advice2" = COALESCE($4, "advice2"),
        "advice3" = COALESCE($5, "advice3"),
        "advice4" = COALESCE($6, "advice4"),
        "advice5" = COALESCE($7, "advice5"),
        "created_at" = COALESCE($8, "created_at"),
        "user_ref" = COALESCE($9, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )

  " Mutations for type 'money_finances' "
  deleteMoney_finances(id: ID!): money_finances
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "money_finances"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertMoney_finances(
    username: String
    score: Float
    notes: String
    action_plan: String
    created_at: DateTime
    user_ref: Int
  ): money_finances
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "money_finances"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateMoney_finances(
    id: ID!
    created_at: DateTime
    score: Float
    notes: String
    action_plan: String
    username: String
    user_ref: Int
  ): money_finances
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "money_finances" SET
        "created_at" = COALESCE($2, "created_at"),
        "score" = COALESCE($3, "score"),
        "username" = COALESCE($4, "username")
        "notes" = COALESCE($5, "notes")
        "action_plan" = COALESCE($6, "action_plan")
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )

" Mutations for type 'money_finances_feedback' "
  deleteMoney_finances_feedback(id: ID!): money_finances_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "money_finances_feedback"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertMoney_finances_feedback(
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ):
  money_finances_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "money_finances_feedback"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateMoney_finances_feedback(
    id: ID!
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ): 
  money_finances_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "money_finances_feedback" SET
        "feedback" = COALESCE($2, "feedback")
        "advice1" = COALESCE($3, "advice1"),
        "advice2" = COALESCE($4, "advice2"),
        "advice3" = COALESCE($5, "advice3"),
        "advice4" = COALESCE($6, "advice4"),
        "advice5" = COALESCE($7, "advice5"),
        "created_at" = COALESCE($8, "created_at"),
        "user_ref" = COALESCE($9, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )

  " Mutations for type 'overall_score' "
  deleteOverall_score(id: ID!): overall_score
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "overall_score"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertOverall_score(
    username: String
    overall_score: Float
    created_at: DateTime
    user_ref: Int
  ):
  overall_score
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "overall_score"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateOverall_score(
    id: ID!
    username: String
    overall_score: Float
    created_at: DateTime
    user_ref: Int
  ): 
  overall_score
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "overall_score" SET
        "career_work_id" = COALESCE($2, "career_work_id"),
        "community_id" = COALESCE($3, "community_id"),
        "created_at" = COALESCE($4, "created_at"),
        "environment_id" = COALESCE($5, "environment_id"),
        "family_friends_id" = COALESCE($6, "family_friends_id"),
        "fun_relaxation_id" = COALESCE($7, "fun_relaxation_id"),
        "growth_learning_id" = COALESCE($8, "growth_learning_id"),
        "health_fitness_id" = COALESCE($9, "health_fitness_id"),
        "money_finances_id" = COALESCE($11, "money_finances_id"),
        "overall_id" = COALESCE($12, "overall_id"),
        "partner_love_id" = COALESCE($13, "partner_love_id"),
        "spirituality_id" = COALESCE($14, "spirituality_id"),
        "username" = COALESCE($15, "username")
        "user_ref" = COALESCE($16, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )
    
  " Mutations for type 'overall_advice' "
  deleteOverall_advice(id: ID!): overall_advice
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "overall_advice"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertOverall_advice(
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    created_at: DateTime
    user_ref: Int
  ):
  overall_advice
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "overall_advice"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateOverall_advice(
    id: ID!
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    created_at: DateTime
    user_ref: Int
  ): 
  overall_advice
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "overall_advice" SET
        "advice1" = COALESCE($2, "advice1"),
        "advice2" = COALESCE($3, "advice2"),
        "advice3" = COALESCE($4, "advice3"),
        "advice4" = COALESCE($5, "advice4"),
        "created_at" = COALESCE($6, "created_at"),
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )

  " Mutations for type 'partner_love' "
  deletePartner_love(id: ID!): partner_love
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "partner_love"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertPartner_love(
    username: String
    score: Float
    notes: String
    action_plan: String
    created_at: DateTime
    user_ref: Int
  ): partner_love
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "partner_love"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updatePartner_love(
    id: ID!
    created_at: DateTime
    score: Float
    notes: String
    action_plan: String
    username: String
    user_ref: Int
  ): partner_love
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "partner_love" SET
        "created_at" = COALESCE($2, "created_at"),
        "score" = COALESCE($3, "score"),
        "username" = COALESCE($4, "username")
        "notes" = COALESCE($5, "notes")
        "action_plan" = COALESCE($6, "action_plan")
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


" Mutations for type 'partner_love_feedback' "
  deletePartner_love_feedback(id: ID!): partner_love_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "partner_love_feedback"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertPartner_love_feedback(
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ):
  partner_love_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "partner_love_feedback"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updatePartner_love_feedback(
    id: ID!
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ): 
  partner_love_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "partner_love_feedback" SET
        "feedback" = COALESCE($2, "feedback")
        "advice1" = COALESCE($3, "advice1"),
        "advice2" = COALESCE($4, "advice2"),
        "advice3" = COALESCE($5, "advice3"),
        "advice4" = COALESCE($6, "advice4"),
        "advice5" = COALESCE($7, "advice5"),
        "created_at" = COALESCE($8, "created_at"),
        "user_ref" = COALESCE($9, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


  " Mutations for type 'spirituality' "
  deleteSpirituality(id: ID!): spirituality
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "spirituality"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertSpirituality(
    username: String
    score: Float
    notes: String
    action_plan: String
    created_at: DateTime
    user_ref: Int
  ): spirituality
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "spirituality"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateSpirituality(
    id: ID!
    created_at: DateTime
    score: Float
    notes: String
    action_plan: String
    username: String
    user_ref: Int
  ): spirituality
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "spirituality" SET
        "created_at" = COALESCE($2, "created_at"),
        "score" = COALESCE($3, "score"),
        "username" = COALESCE($4, "username")
        "notes" = COALESCE($5, "notes")
        "action_plan" = COALESCE($6, "action_plan")
        "user_ref" = COALESCE($7, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )

" Mutations for type 'spirituality_feedback' "
  deleteSpirituality_feedback(id: ID!): spirituality_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "spirituality_feedback"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertSpirituality_feedback(
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ):
  spirituality_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "spirituality_feedback"
      dml: INSERT
      configuration: "postgresql_config"
    )
  updateSpirituality_feedback(
    id: ID!
    feedback: String
    advice1: String
    advice2: String
    advice3: String
    advice4: String
    advice5: String
    created_at: DateTime
    user_ref: Int
  ): 
  spirituality_feedback
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "spirituality_feedback" SET
        "feedback" = COALESCE($2, "feedback")
        "advice1" = COALESCE($3, "advice1"),
        "advice2" = COALESCE($4, "advice2"),
        "advice3" = COALESCE($5, "advice3"),
        "advice4" = COALESCE($6, "advice4"),
        "advice5" = COALESCE($7, "advice5"),
        "created_at" = COALESCE($8, "created_at"),
        "user_ref" = COALESCE($9, "user_ref")
      WHERE
        "id" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )


  " Mutations for type 'users' "
  deleteUsers(email: String!): users
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "users"
      dml: DELETE
      configuration: "postgresql_config"
    )
  insertUsers(
    username: String
    email: String
    created_at: DateTime
    password: String
    provider: String
  ): users
    @dbquery(
      type: "postgresql"
      schema: "public"
      table: "users"
      dml: INSERT
      configuration: "postgresql_config"
    )
    updateUsers(
    email: String!
    isActive: Boolean
  ): users
    @dbquery(
      type: "postgresql"
      schema: "public"
      query: """
      UPDATE "users" SET
        "isActive" = COALESCE($2, "isActive")
      WHERE
        "email" = $1
      RETURNING *
      """
      configuration: "postgresql_config"
    )

}



